### ISSUE TITLE
Enable issues on YACHT

### ISSUE THREAD

**Issue by gregorysprenger** [KoslickiLab/Estimating_Unknowns#11]
# Current

When a repo is forked, the default setting for `Issues` is off.

# Expected

Be able to make issues on YACHT repo and not where it is forked (like this issue). To enable, go to YACHT -> Settings -> Scroll down to the `Features` section and check the Issues box to enable them.

**Comment by dkoslicki** [comment]
Repo renamed, [moved](https://github.com/KoslickiLab/YACHT), and issues enabled!
